# Generated by Django 2.0.1 on 2018-04-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.AutoField(db_column='bookId', primary_key=True, serialize=False)),
                ('bookname', models.CharField(db_column='bookName', max_length=30)),
                ('bookauthor', models.CharField(db_column='bookAuthor', max_length=10)),
                ('lastupdate', models.CharField(blank=True, db_column='lastUpdate', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chapacter',
            fields=[
                ('chapid', models.AutoField(db_column='chapId', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'Chapacter',
                'managed': False,
            },
        ),
    ]
